name: WakaTime Readme Update

on:
  schedule:
    - cron: "0 */6 * * *" 
  workflow_dispatch:

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update WakaTime in README
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SECTION_NAME: wakatime
          BLOCKS: ░▒▓█
          LANG_COUNT: 5
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true

      - name: Append Last Update Footnote
        env:
          TZ: "Asia/Ho_Chi_Minh"
        run: |
          sed -i '/last update:/I d' README.md
          
          echo -e "\n<sub>_This readme updates every 6 hours - last update: $(date +'%Y-%m-%d %H:%M:%S') (GMT+7)_</sub>" >> README.md
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "docs: update footnote time" || exit 0
          git push
