name: Hackatime Readme Update

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Hackatime Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol0013/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.HACKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_URL: https://hackatime.hackclub.com/api/hackatime/v1
          SHOW_TITLE: true
          SECTION_NAME: wakatime
          BLOCKS: ░▒▓█
          LANG_COUNT: 5
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_TOTAL: true
